# Generated by Django 5.2.4 on 2025-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_remove_agent_admin_delete_admin_delete_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('jardinier', 'Jardinier'), ('paysagiste', 'Paysagiste'), ('horticulteur', 'Horticulteur'), ('electronicien', 'Électronicien'), ('technicien_iot', 'Technicien IoT'), ('installateur_capteurs', 'Installateur de capteurs'), ('maintenance', 'Agent de maintenance'), ('irrigation', 'Spécialiste irrigation'), ('gestion_energie', 'Gestion de l’énergie'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
    ]
