# Generated by Django 5.2.4 on 2025-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="reset_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
