# Generated by Django 5.2.4 on 2025-08-07 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('arrosage', 'Arrosage'), ('désherbage', 'Désherbage'), ('taillage', 'Taillage')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('à_faire', 'À faire'), ('en_cours', 'En cours'), ('terminée', 'Terminée')], default='à_faire', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='users.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
