# Generated by Django 5.2.4 on 2025-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_task'),
        ('users', '0008_user_reset_token_user_reset_token_expires'),
    ]

    operations = [
    ]
