# Generated by Django 5.2.4 on 2025-08-12 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_id', models.CharField(help_text='ID complet OpenStreetMap', max_length=50, unique=True)),
                ('osm_id', models.CharField(help_text='ID OpenStreetMap', max_length=20)),
                ('osm_type', models.CharField(help_text="Type d'objet OSM (way, node, relation)", max_length=10)),
                ('leisure', models.CharField(blank=True, help_text='Type de loisir (garden, park, etc.)', max_length=50, null=True)),
                ('landuse', models.CharField(blank=True, help_text='Usage du terrain', max_length=50, null=True)),
                ('name', models.CharField(blank=True, help_text="Nom de l'espace vert", max_length=200, null=True)),
                ('fee', models.CharField(blank=True, help_text="Frais d'entrée", max_length=10, null=True)),
                ('access', models.CharField(blank=True, help_text="Type d'accès", max_length=50, null=True)),
                ('barrier', models.CharField(blank=True, help_text='Barrières', max_length=50, null=True)),
                ('wikimedia_commons', models.URLField(blank=True, help_text='Lien Wikimedia Commons', null=True)),
                ('wikidata', models.CharField(blank=True, help_text='ID Wikidata', max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text="Géométrie de l'espace vert", srid=4326)),
            ],
            options={
                'verbose_name': 'Espace Vert',
                'verbose_name_plural': 'Espaces Verts',
                'indexes': [models.Index(fields=['geometry'], name='green_space_geometr_f47978_idx'), models.Index(fields=['leisure'], name='green_space_leisure_46a51c_idx'), models.Index(fields=['landuse'], name='green_space_landuse_959613_idx')],
            },
        ),
    ]
